<link rel="preload" href="<?= urlRedirect('/public/assets/fonts/VAGRoundedNext/VAGRoundedNext-Regular.woff') ?>" as="font" type="font/woff" crossorigin="anonymous">
<link rel="preload" href="<?= urlRedirect('/public/assets/fonts/VAGRoundedNext/VAGRoundedNext-ExtraLight.woff') ?>" as="font" type="font/woff" crossorigin="anonymous">
<link rel="preload" href="<?= urlRedirect('/public/assets/fonts/VAGRoundedNext/VAGRoundedNext-Light.woff') ?>" as="font" type="font/woff" crossorigin="anonymous">
<link rel="preload" href="<?= urlRedirect('/public/assets/fonts/VAGRoundedNext/VAGRoundedNext-Medium.woff') ?>" as="font" type="font/woff" crossorigin="anonymous">
<link rel="preload" href="<?= urlRedirect('/public/assets/fonts/VAGRoundedNext/VAGRoundedNext-SemiBold.woff') ?>" as="font" type="font/woff" crossorigin="anonymous">
<link rel="preload" href="<?= urlRedirect('/public/assets/fonts/VAGRoundedNext/VAGRoundedNext-Bold.woff') ?>" as="font" type="font/woff" crossorigin="anonymous">
<link rel="preload" href="<?= urlRedirect('/public/assets/fonts/VAGRoundedNext/VAGRoundedNext-Black.woff') ?>" as="font" type="font/woff" crossorigin="anonymous">
<link rel="preload" href="<?= urlRedirect('/public/assets/fonts/VAGRoundedNext/VAGRoundedNext-Heavy.woff') ?>" as="font" type="font/woff" crossorigin="anonymous">
<link rel="preload" href="<?= urlRedirect('/public/assets/fonts/VAGRoundedNext/VAGRoundedNext-ExtraBlack.woff') ?>" as="font" type="font/woff" crossorigin="anonymous">
<link rel="preload" href="<?= urlRedirect('/public/assets/fonts/VAGRoundedNext/VAGRoundedNext-Thin.woff') ?>" as="font" type="font/woff" crossorigin="anonymous">