status:
  uncategorized: Sin categoría
  in_progress: En progreso
  pending: Pendiente
  resolved: Resuelto
  closed: Cerrado
  denied: Denegado

priority:
  low: Baja
  moderate: Moderada
  medium: Media
  high: Alta
  urgent: Urgente

type:
  not_defined: No definido
  incident: Ticket de Incidente
  problem: Ticket de Problema
  service_request: Ticket de Solicitud de Servicio
  change: Ticket de Cambio
  task: Ticket de Tarea
  meeting: Ticket de Reuniones

category:
  not_defined: No definido
  user: Usuario
  hardware: Hardware
  software: Software
  network: Redes
  server: Servidor
  security: Seguridad
  cloud_services: Servicios en la nube
  other: Otros